(()=>{
'use strict';
const FRAME_PATCH='10.0.5';
const FRAME_META_KEY='blue_symbiote_frame_meta_v10_5';
const q=id=>document.getElementById(id);
const nrm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const safe=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let sourceVideoFile=null,sourceVideoURL='',sourceVideoEl=null,activeSourceId='',frameMeta={};
try{frameMeta=JSON.parse(localStorage.getItem(FRAME_META_KEY)||'{}')||{}}catch(e){frameMeta={}}
function baseCanon(ex){try{if(typeof canon==='function')return canon(ex)}catch(e){}return ex?.canonical||nrm(ex?.name)}
function klass(){try{return typeof currentClass!=='undefined'?currentClass:null}catch(e){return null}}
function app(){return window.APP||null}
function vimgs(ex){try{if(typeof visualImagesFor==='function')return visualImagesFor(ex)||[]}catch(e){}return[]}
function saveMeta(){try{localStorage.setItem(FRAME_META_KEY,JSON.stringify(frameMeta))}catch(e){}}
function flatClass(){const c=klass();if(c?.blocks)return c.blocks.flatMap((b,bi)=>b.exercises.map((ex,ei)=>({ex,bi,ei,block:b.phase})));return[]}
function sourceForExercise(ex){const A=app();if(!A)return null;return (A.videos||[]).find(v=>v.sourcePool&&v.sourcePool===ex.source)||null}
function sourceExercises(video){const A=app();if(!A||!video?.sourcePool)return[];return (A.exercises||[]).filter(ex=>ex.source===video.sourcePool)}
function extractedSources(){const A=app();return (A?.videos||[]).filter(v=>v.status==='EXTRAÍDO'&&v.sourcePool)}
function dynamicEx(ex){return />|→|wave|swing|clean|snatch|rotation|rotacao|crawl|cars|lunge|squat|reach|transition|flow/i.test([ex?.name,ex?.pattern].join(' '))}
function haveFrame(ex){return vimgs(ex).length>0}
function injectStyle(){if(q('framePatchStyle'))return;const st=document.createElement('style');st.id='framePatchStyle';st.textContent=`.frameBar{display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin:10px 0}.frameBtn{background:#17324a;color:#fff;border:0;border-radius:10px;padding:10px 13px;font-weight:800;cursor:pointer}.frameBtn.secondary{background:#eef4f8;color:#17324a;border:1px solid #b9cbd8}.framePill{display:inline-flex;align-items:center;gap:5px;padding:4px 7px;border-radius:999px;background:#e8f4ff;color:#0b5f9e;font-size:11px;font-weight:800}.frameModal{position:fixed;inset:0;background:rgba(7,18,28,.66);z-index:99999;display:none;align-items:flex-start;justify-content:center;padding:18px;overflow:auto}.frameModal.open{display:flex}.framePanel{width:min(900px,100%);background:#fff;border-radius:16px;padding:16px;box-shadow:0 22px 70px rgba(0,0,0,.25)}.frameGrid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.framePanel video{width:100%;max-height:430px;background:#111;border-radius:12px}.framePanel input,.framePanel select{width:100%;box-sizing:border-box;padding:9px;border:1px solid #c9d5dd;border-radius:9px}.frameStatus{padding:10px;border-radius:10px;background:#edf6ee;margin:9px 0;line-height:1.45}.frameWarn{background:#fff5e5}.flashBadge{position:absolute;left:7px;bottom:7px;background:rgba(11,95,158,.9);color:#fff;font-size:10px;font-weight:800;padding:4px 7px;border-radius:999px}.imgbox{position:relative}.frameCardAction{margin-left:4px}@media(max-width:650px){.frameGrid{grid-template-columns:1fr}.framePanel{padding:12px}.frameBar .frameBtn{flex:1 1 45%}}`;document.head.appendChild(st)}
function ensureModal(){if(q('frameModal'))return;const div=document.createElement('div');div.id='frameModal';div.className='frameModal';div.innerHTML=`<div class="framePanel"><div style="display:flex;justify-content:space-between;gap:12px;align-items:start"><div><h2 style="margin:0">FLASHES DOS EXERCÍCIOS</h2><div class="small" style="margin-top:4px">Frames reais do vídeo → biblioteca visual → reutilização automática nas aulas futuras.</div></div><button class="frameBtn secondary" id="frameClose">FECHAR</button></div><div id="frameStatus" class="frameStatus">A preparar…</div><div class="frameGrid"><div><label><b>Fonte extraída</b></label><select id="frameSource"></select></div><div><label><b>Vídeo fonte no dispositivo</b></label><input id="frameFile" type="file" accept="video/*"></div><div><label><b>Início útil do vídeo (segundos)</b></label><input id="frameStart" type="number" min="0" value="0" step="1"></div><div><label><b>Fim útil (segundos)</b></label><input id="frameEnd" type="number" min="0" value="0" step="1"></div></div><div class="frameBar"><button class="frameBtn" id="frameAuto">AUTO-EXTRAIR FRAMES</button><button class="frameBtn secondary" id="frameFill">PREENCHER AULA COM BIBLIOTECA</button><button class="frameBtn secondary" id="frameOpenSource">ABRIR FONTE</button></div><video id="frameVideo" controls playsinline preload="metadata"></video><div class="small" style="margin-top:9px"><b>Como funciona:</b> num vídeo já extraído, a app conhece a ordem dos exercícios. Carregas o vídeo uma vez e ela percorre-o, captura 1–2 frames por exercício, guarda-os no próprio dispositivo e passa a reutilizá-los automaticamente. Para YouTube, o browser não permite copiar pixels do vídeo diretamente por segurança; por isso a captura exata usa o ficheiro de vídeo no dispositivo.</div></div>`;document.body.appendChild(div);q('frameClose').onclick=()=>div.classList.remove('open');div.addEventListener('click',e=>{if(e.target===div)div.classList.remove('open')});const sel=q('frameSource');extractedSources().forEach(v=>{const o=document.createElement('option');o.value=v.id;o.textContent=`${v.creator} — ${v.title}`;sel.appendChild(o)});sel.onchange=()=>{activeSourceId=sel.value;updateModalStatus()};q('frameFile').onchange=loadLocalVideo;q('frameAuto').onclick=autoExtract;q('frameFill').onclick=()=>{paintFrames();updateModalStatus('Biblioteca aplicada à aula.')};q('frameOpenSource').onclick=openSource;sourceVideoEl=q('frameVideo');sourceVideoEl.onloadedmetadata=()=>{q('frameEnd').value=Math.max(0,Math.floor(sourceVideoEl.duration||0));updateModalStatus('Vídeo carregado. Pronto para auto-extração.')}}
function currentVideo(){const c=klass();if(c?.video?.id)return (app()?.videos||[]).find(v=>v.id===c.video.id)||c.video;const id=activeSourceId||q('frameSource')?.value;return (app()?.videos||[]).find(v=>v.id===id)||null}
function setDefaultSource(){ensureModal();const c=klass(),sel=q('frameSource');let id=c?.video?.status==='EXTRAÍDO'?c.video.id:'';if(!id){const miss=flatClass().find(x=>!haveFrame(x.ex));const sv=miss?sourceForExercise(miss.ex):null;if(sv?.status==='EXTRAÍDO')id=sv.id}if(id&&[...sel.options].some(o=>o.value===id))sel.value=id;activeSourceId=sel.value;updateModalStatus()}
function openFrameModal(){setDefaultSource();q('frameModal').classList.add('open')}
function updateModalStatus(msg=''){const box=q('frameStatus');if(!box)return;const v=currentVideo();const xs=flatClass();const filled=xs.filter(x=>haveFrame(x.ex)).length;const total=xs.length;const sx=v?sourceExercises(v):[];box.className='frameStatus'+(!v?' frameWarn':'');box.innerHTML=msg?safe(msg):v?`<b>${safe(v.creator)} — ${safe(v.title)}</b><br>Fonte extraída: ${sx.length} ocorrências · aula atual: ${filled}/${total} exercícios já com imagem.`:`Não encontrei uma fonte extraída para esta aula. A app continua a usar automaticamente todas as imagens/frames já guardados na biblioteca.`}
function openSource(){const v=currentVideo();if(!v)return alert('Seleciona uma fonte.');window.open('https://www.youtube.com/watch?v='+encodeURIComponent(v.id),'_blank','noopener')}
function loadLocalVideo(e){const f=e.target.files?.[0];if(!f)return;sourceVideoFile=f;if(sourceVideoURL)URL.revokeObjectURL(sourceVideoURL);sourceVideoURL=URL.createObjectURL(f);sourceVideoEl.src=sourceVideoURL;sourceVideoEl.load()}
function seekVideo(sec){return new Promise((resolve,reject)=>{const v=sourceVideoEl;if(!v||!Number.isFinite(v.duration))return reject(new Error('Vídeo não carregado.'));const t=Math.max(0,Math.min(v.duration-.05,sec));let done=false;const finish=()=>{if(done)return;done=true;v.removeEventListener('seeked',finish);resolve()};v.addEventListener('seeked',finish,{once:true});v.currentTime=t;setTimeout(finish,1800)})}
function capture(){const v=sourceVideoEl;if(!v?.videoWidth)throw new Error('Frame indisponível.');const max=760,scale=Math.min(1,max/v.videoWidth),w=Math.max(1,Math.round(v.videoWidth*scale)),h=Math.max(1,Math.round(v.videoHeight*scale));const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(v,0,0,w,h);return c.toDataURL('image/webp',.84)}
async function storeFrame(ex,arr,meta){const key=baseCanon(ex);let ok=false;try{if(typeof putVisual==='function'){await putVisual(key,arr);ok=true}}catch(e){console.warn('putVisual falhou',e)}if(!ok){try{const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('blue_symbiote_visual_v7',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('exercise_images'))r.result.createObjectStore('exercise_images')};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});await new Promise((resolve,reject)=>{const tx=db.transaction('exercise_images','readwrite');tx.objectStore('exercise_images').put(arr,key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close();ok=true}catch(e){console.warn(e)}}frameMeta[key]={...(frameMeta[key]||{}),...meta,updatedAt:Date.now()};saveMeta();return ok}
async function autoExtract(){const v=currentVideo();if(!v)return alert('Seleciona uma fonte extraída.');if(!sourceVideoFile||!sourceVideoEl?.duration)return alert('Carrega primeiro o vídeo fonte no dispositivo.');const occurrences=sourceExercises(v);if(!occurrences.length)return alert('Esta fonte não tem sequência extraída na biblioteca.');const start=Math.max(0,+q('frameStart').value||0),end=Math.min(sourceVideoEl.duration,+q('frameEnd').value||sourceVideoEl.duration);if(end<=start+5)return alert('Intervalo do vídeo inválido.');const usable=end-start;let done=0,failed=0;const unique=new Set();q('frameAuto').disabled=true;try{for(let i=0;i<occurrences.length;i++){const ex=occurrences[i],key=baseCanon(ex);if(unique.has(key)&&haveFrame(ex))continue;unique.add(key);const a=start+usable*(i/occurrences.length),b=start+usable*((i+1)/occurrences.length);const ratios=dynamicEx(ex)?[.36,.68]:[.52],frames=[];for(const r of ratios){await seekVideo(a+(b-a)*r);try{frames.push(capture())}catch(e){failed++;break}}if(frames.length){await storeFrame(ex,frames,{sourceId:v.id,sourcePool:v.sourcePool,sourceTitle:v.title,creator:v.creator,method:'AUTO_LOCAL_VIDEO',approxTime:Math.round(a+(b-a)*.52),count:frames.length});done++}q('frameStatus').innerHTML=`A extrair… <b>${done}</b> exercícios guardados${failed?' · '+failed+' falhas':''}.`;await new Promise(r=>setTimeout(r,10))}try{if(typeof renderVisualLibrary==='function')renderVisualLibrary();if(typeof renderBuild==='function')renderBuild();if(typeof renderFollow==='function')renderFollow()}catch(e){}paintFrames();updateModalStatus(`Concluído: ${done} exercícios receberam frames reais desta fonte${failed?' · '+failed+' falhas':''}.`)}finally{q('frameAuto').disabled=false}}
function findExerciseByCard(card){const title=card.querySelector('.exname')?.textContent||'';const name=title.replace(/^\s*\d+(?:\.\d+)?\s*[—-]\s*/,'').trim();const A=app();if(!name||!A)return null;return (A.exercises||[]).find(ex=>nrm(ex.name)===nrm(name))||(A.exercises||[]).find(ex=>nrm(name).includes(nrm(ex.name))||nrm(ex.name).includes(nrm(name)))||null}
function paintCard(card,ex){const box=card.querySelector('.imgbox');if(!box||!ex)return;const imgs=vimgs(ex);if(imgs.length){const key=baseCanon(ex),m=frameMeta[key];if(m&&!box.querySelector('.flashBadge')){const b=document.createElement('span');b.className='flashBadge';b.textContent='FRAME VÍDEO';box.appendChild(b)}return}const sv=sourceForExercise(ex);if(sv&&!box.dataset.sourceFallback){box.dataset.sourceFallback='1';const ph=box.querySelector('.placeholder');if(ph)ph.innerHTML=`<div style="font-weight:800">FLASH AINDA NÃO CAPTURADO</div><small>${safe(sv.creator)} · usar AUTO-FRAMES</small>`}}
function addCardButton(card,ex){const controls=card.querySelector('.controls');if(!controls||controls.querySelector('.frameCardAction'))return;const b=document.createElement('button');b.className='btn frameCardAction';b.textContent='FLASH';b.onclick=()=>{const sv=sourceForExercise(ex);ensureModal();if(sv&&q('frameSource'))q('frameSource').value=sv.id;activeSourceId=sv?.id||'';openFrameModal()};controls.appendChild(b)}
function paintFrames(){document.querySelectorAll('#blocks .exercise,#scrollMode .exercise').forEach(card=>{const ex=findExerciseByCard(card);if(ex){paintCard(card,ex);addCardButton(card,ex)}});const c=klass();if(c&&q('frameCoverage')){const xs=flatClass(),n=xs.filter(x=>haveFrame(x.ex)).length;q('frameCoverage').textContent=`IMAGENS ${n}/${xs.length}`}}
function addToolbar(){const build=q('build');if(!build||q('autoFrameBtn'))return;const source=q('sourceBox')||build.firstElementChild;const bar=document.createElement('div');bar.className='frameBar noprint';bar.innerHTML='<button class="frameBtn" id="autoFrameBtn">AUTO-FRAMES</button><button class="frameBtn secondary" id="applyFrameBtn">PREENCHER IMAGENS</button><span class="framePill" id="frameCoverage">IMAGENS 0/0</span>';source.insertAdjacentElement('afterend',bar);q('autoFrameBtn').onclick=openFrameModal;q('applyFrameBtn').onclick=()=>{try{if(typeof renderBuild==='function')renderBuild();if(typeof renderFollow==='function')renderFollow()}catch(e){}setTimeout(paintFrames,80)}}
function improveSuggestions(){document.querySelectorAll('#suggestions .suggestion').forEach(card=>{const title=card.querySelector('.sugtitle')?.textContent||'';const v=(app()?.videos||[]).find(x=>x.title===title);const thumb=card.querySelector('.thumb');if(v?.thumbnail&&thumb&&!thumb.querySelector('img')){const im=document.createElement('img');im.src=v.thumbnail;im.alt='';im.loading='lazy';im.style.cssText='width:100%;height:100%;object-fit:cover;border-radius:inherit';thumb.innerHTML='';thumb.appendChild(im)}})}
function addVisualNote(){const view=q('visual');if(!view||q('frameVisualNote'))return;const card=view.querySelector('.card');if(!card)return;const d=document.createElement('div');d.id='frameVisualNote';d.className='storageNote';d.style.marginTop='8px';d.innerHTML='<b>Frames reais:</b> imagens capturadas pelo AUTO-FRAMES ficam nesta mesma biblioteca visual e passam a aparecer automaticamente sempre que o exercício voltar a ser usado.';card.appendChild(d)}
function version(){const h=document.querySelector('header h1');if(h)h.textContent='BLUE SYMBIOTE v10.0.5';const sub=document.querySelector('header .sub');if(sub)sub.textContent='instalável · auto-update · filtros livres · TRAINING LAB · AUTO-FRAMES · BLUE EDU'}
function observe(){const mo=new MutationObserver(()=>{paintFrames();improveSuggestions()});['blocks','scrollMode','suggestions'].forEach(id=>{const el=q(id);if(el)mo.observe(el,{childList:true,subtree:true})})}
function init(){if(!app()||!q('build')){setTimeout(init,100);return}injectStyle();ensureModal();addToolbar();addVisualNote();version();observe();setTimeout(()=>{paintFrames();improveSuggestions()},100);console.info('BLUE AUTO-FRAMES '+FRAME_PATCH+' ativo')}
init();
})();