(()=>{
'use strict';
const SOCIAL_VERSION='10.0.6';
const SOCIAL_KEY='blue_symbiote_social_v10_6';
const $s=id=>document.getElementById(id);
const norm6=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const esc6=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const SOCIAL_BANK=[
 {id:'MIRROR',name:'Espelho em pares — movimento e reação',eq:'bodyweight',per:2,format:'Pares',rpe:3,doms:0,position:'Em pé',pattern:'Coordenação / reação',objective:'Aquecer, comunicar e coordenar sem fadiga alta.',rule:'Em pares: A lidera movimentos simples durante 30–40 s; B copia. Trocam o líder. Usar passos laterais, reaches, hinge suave, squat curto e rotações controladas.'},
 {id:'TRAFFIC',name:'Semáforo de movimento',eq:'bodyweight',per:99,format:'Grupo',rpe:4,doms:0,position:'Em pé',pattern:'Reação / deslocamento',objective:'Elevar a temperatura corporal com atenção e tomada de decisão.',rule:'Verde = deslocar; amarelo = marcha/step touch; vermelho = parar e fazer 1 movimento indicado. Variar direção e padrão sem transformar em sprint.'},
 {id:'NUMBER_DIR',name:'Números e direções',eq:'bodyweight',per:99,format:'Grupo',rpe:4,doms:0,position:'Em pé',pattern:'Coordenação / agilidade',objective:'Trabalhar reação, orientação espacial e componente lúdica.',rule:'Cada número corresponde a uma direção ou tarefa simples. O treinador chama o número e o grupo reage. Manter deslocamentos curtos e técnica fácil.'},
 {id:'TEAM_SUM',name:'Missão de equipa — somar repetições',eq:'bodyweight',per:4,format:'Equipas',rpe:5,doms:1,position:'Em pé',pattern:'Full body cooperativo',objective:'Criar trabalho de equipa sem competição agressiva.',rule:'Equipas de 3–4 acumulam um objetivo coletivo com reps curtas e tecnicamente simples. Um trabalha, outro prepara, outro conta/apoia; rodar rapidamente.'},
 {id:'PASS_SQUAT',name:'Roda — passe + squat',eq:'ball',per:4,format:'Roda',rpe:5,doms:1,position:'Em pé',pattern:'Squat / passe / reação',objective:'Combinar agachamento, coordenação e interação social.',rule:'Roda de 3–4. Passar a bola; quem recebe faz 1 squat controlado com a bola ao peito e passa a outro elemento. Progredir para squat + press leve se fizer sentido.'},
 {id:'PASS_MOVE',name:'Passe e troca de lugar',eq:'ball',per:4,format:'Roda',rpe:5,doms:0,position:'Em pé',pattern:'Passe / locomotion',objective:'Manter o grupo em movimento com baixa carga muscular residual.',rule:'Depois de passar a bola, trocar de lugar com outro elemento da roda. Variar passe de peito, bounce pass e deslocamento lateral.'},
 {id:'BALL_REACT',name:'Bola ao centro — nome, reação e tarefa',eq:'ball',per:5,format:'Roda',rpe:5,doms:0,position:'Em pé',pattern:'Reação / aceleração curta',objective:'Treinar atenção e resposta rápida sem volume elevado.',rule:'Bola ao centro. O treinador ou colega chama um nome; essa pessoa reage, recolhe/toca na bola e executa uma tarefa curta antes de voltar à posição.'},
 {id:'BALL_TARGET',name:'Passe ao alvo + deslocamento',eq:'ball',per:4,format:'Equipas',rpe:5,doms:0,position:'Em pé',pattern:'Precisão / deslocamento',objective:'Adicionar precisão, coordenação e movimento contínuo.',rule:'Em equipas pequenas, passar a bola para um alvo/colega e deslocar para uma nova posição. Pontuar consistência, não velocidade máxima.'},
 {id:'CONE_MEMORY',name:'Memória dos cones',eq:'cones',per:3,format:'Equipas',rpe:5,doms:0,position:'Em pé',pattern:'Reação / memória / deslocamento',objective:'Estimular cognição e movimento moderado.',rule:'Cones com cores/números. O treinador dá uma sequência curta e a equipa reproduz tocando nos cones pela ordem correta. Alternar quem executa.'},
 {id:'CONE_RELAY',name:'Relay cooperativo de cones',eq:'cones',per:4,format:'Equipas',rpe:6,doms:0,position:'Em pé',pattern:'Locomotion / relay',objective:'Criar conditioning moderado com participação coletiva.',rule:'Cada elemento desloca-se até um cone, cumpre uma tarefa simples e regressa para libertar o colega. Vence a execução consistente, não o sprint.'},
 {id:'CONE_MIRROR',name:'Espelho com cones em pares',eq:'cones',per:2,format:'Pares',rpe:5,doms:0,position:'Em pé',pattern:'Agilidade / espelho',objective:'Coordenação, reação e trabalho em pares.',rule:'Dois cones delimitam a zona. A lidera movimentos laterais curtos e B acompanha. Trocar ao sinal. Evitar mudanças de direção máximas.'},
 {id:'KB_RELAY',name:'Relay de carry com kettlebell',eq:'kb',per:4,format:'Equipas',rpe:6,doms:1,position:'Em pé',pattern:'Carry / locomotion',objective:'Trabalhar grip, core e deslocamento com carga simples.',rule:'Equipas de 3–4. Carry curto até marca e retorno; entregar a kettlebell ao colega de forma controlada. Alternar lado/posição conforme objetivo.'},
 {id:'KB_HANDOFF',name:'Kettlebell hand-off em equipa',eq:'kb',per:4,format:'Roda',rpe:5,doms:1,position:'Em pé',pattern:'Hinge / hand-off',objective:'Criar cooperação com carga sem complexidade excessiva.',rule:'Em círculo pequeno, transportar/entregar a KB de forma controlada após um hinge ou deadlift curto. Nunca lançar a carga.'},
 {id:'TRX_PAIR',name:'TRX em pares — alternância ativa',eq:'trx',per:4,format:'Pares',rpe:6,doms:1,position:'Em pé',pattern:'Pull / squat / alternância',objective:'Usar suspensão sem criar filas longas.',rule:'Um executa 20–30 s de row ou squat assistido; o parceiro faz marcha, mobilidade ou tarefa leve. Trocar imediatamente. Uma estação por 3–4 pessoas no máximo.'},
 {id:'TRX_MIRROR',name:'TRX espelho — controlo em pares',eq:'trx',per:4,format:'Pares',rpe:5,doms:0,position:'Em pé',pattern:'Suspensão / controlo',objective:'Trabalhar técnica e comunicação com baixa fadiga.',rule:'Um elemento usa o TRX com amplitude confortável enquanto o parceiro reproduz o padrão sem equipamento e dá feedback simples. Trocar após 30–40 s.'},
 {id:'BAND_PAIR',name:'Elástico em pares — tensão e resposta',eq:'band',per:2,format:'Pares',rpe:5,doms:1,position:'Em pé',pattern:'Pull / anti-rotação',objective:'Criar resistência simples com cooperação.',rule:'Em pares, usar banda para row, Pallof ou deslocamento lateral curto. Um trabalha, outro estabiliza/ancora quando seguro; trocar frequentemente.'},
 {id:'HANG_TEAM',name:'Barras suspensas — estação cooperativa',eq:'hanging',per:4,format:'Equipas',rpe:6,doms:1,position:'Em pé',pattern:'Hang / pull / core',objective:'Integrar suspensão em pequenos grupos sem filas.',rule:'Estação de 3–4: um executa hang curto, scapular pull ou knee raise simples; restantes fazem tarefa leve complementar. Rodar a cada 20–30 s.'},
 {id:'STEP_SYNC',name:'Step sincronizado em equipa',eq:'step',per:2,format:'Equipas',rpe:6,doms:1,position:'Em pé',pattern:'Step / ritmo',objective:'Conditioning moderado com coordenação coletiva.',rule:'Pares ou trios sincronizam step-ups baixos e simples ao ritmo do treinador. O objetivo é manter cadência comum, não velocidade máxima.'},
 {id:'PLANK_TAP',name:'Plank high-five em pares',eq:'bodyweight',per:2,format:'Pares',rpe:6,doms:1,position:'Prancha',pattern:'Anti-extensão / interação',objective:'Core e estabilidade com componente social.',rule:'Em prancha alta ou versão inclinada, alternar toque de mão com o parceiro. Blocos curtos de 15–25 s; regressar para apoio mais alto quando necessário.'},
 {id:'DEADBUG_PASS',name:'Dead bug + passe em pares',eq:'ball',per:2,format:'Pares',rpe:4,doms:0,position:'Deitado',pattern:'Core / passe',objective:'Core controlado com interação e baixa agressão muscular.',rule:'Em pares próximos, alternar dead bug simples e passe leve de bola. Movimento lento e respirado; a precisão do passe vale mais do que a velocidade.'},
 {id:'SEATED_PASS',name:'Passe sentado + rotação controlada',eq:'ball',per:3,format:'Roda',rpe:4,doms:0,position:'Sentado',pattern:'Rotação / passe',objective:'Coordenação e core em intensidade leve/moderada.',rule:'Sentados em triângulo/roda pequena, passar a bola com rotação torácica controlada. Alternar direção e tipo de passe.'},
 {id:'WALK_TALK',name:'Caminhada em pares + desafio de mobilidade',eq:'bodyweight',per:2,format:'Pares',rpe:3,doms:0,position:'Em pé',pattern:'Locomotion / mobilidade',objective:'Recuperar, socializar e fechar a sessão em movimento.',rule:'Caminhar em pares; ao sinal, parar para uma tarefa leve de mobilidade/respiração e retomar. Ideal para transição ou retorno à calma.'}
];
const EQ_ALIASES={bodyweight:['peso corporal','bodyweight','sem equipamento','corpo'],ball:['bola','ball','medicine ball','med ball'],cones:['cone','cones'],trx:['trx','suspensao','suspensão'],kb:['kettlebell','kettlebells','kb'],bar:['barra','barbell','discos'],hanging:['barra suspensa','barras suspensas','barra fixa','hanging'],band:['elastico','elástico','elasticos','elásticos','band','miniband','mini band'],dumbbell:['halter','halteres','dumbbell'],step:['step'],slider:['slider','sliders','disco deslizante'],bosu:['bosu']};
function socialCfg(){return{pct:+($s('socialMix')?.value||0),finish:$s('finishState')?.value||'Ativos',inventory:$s('roomInventory')?.value||'',format:$s('socialFormat')?.value||'Automático'}}
function addSocialFields(){const grid=$s('classType')?.closest('.grid');if(!grid||$s('socialMix'))return;const wrap=document.createElement('div');wrap.id='socialConfigBlock';wrap.className='card';wrap.style.marginTop='12px';wrap.innerHTML=`<h2 style="margin-top:0">2) Interação / componente social</h2><div class="grid"><div class="field"><label>Componente social/cooperativa</label><select id="socialMix"><option value="0" selected>0% · Convencional</option><option value="25">25% · Mescla leve</option><option value="50">50% · Híbrida</option><option value="75">75% · Predominante</option><option value="100">100% · Aula social inteira</option></select></div><div class="field"><label>Como queres que saiam?</label><select id="finishState"><option>Leves</option><option selected>Ativos</option><option>Treinados</option><option>Puxado</option></select></div><div class="field"><label>Formato social</label><select id="socialFormat"><option selected>Automático</option><option>Pares</option><option>Roda</option><option>Equipas</option><option>Grupo</option></select></div><div class="field"><label>Material realmente disponível</label><input id="roomInventory" type="text" placeholder="Ex.: 3 bolas, 4 TRX, 6 kettlebells, 8 cones, peso corporal"></div></div><div id="socialInventoryHint" class="storageNote" style="margin-top:9px"><b>Regra:</b> a app só usa dinâmicas sociais compatíveis com o material e quantidades indicadas, procurando evitar filas e tempos mortos. Podes fazer apenas um bloco social ou uma aula inteira.</div>`;const card=grid.closest('.card');card.insertAdjacentElement('afterend',wrap);let saved={};try{saved=JSON.parse(localStorage.getItem(SOCIAL_KEY)||'{}')||{}}catch(e){}for(const [id,v] of Object.entries(saved)){if($s(id)&&v!=null)$s(id).value=v}['socialMix','finishState','socialFormat','roomInventory','groupSize','equipment'].forEach(id=>{const el=$s(id);if(!el)return;el.addEventListener('input',()=>{saveSocial();inventoryHint()});el.addEventListener('change',()=>{saveSocial();inventoryHint()})});inventoryHint()}
function saveSocial(){const o={};['socialMix','finishState','socialFormat','roomInventory'].forEach(id=>{if($s(id))o[id]=$s(id).value});try{localStorage.setItem(SOCIAL_KEY,JSON.stringify(o))}catch(e){}}
function parseInventory(){const raw=[socialCfg().inventory,$s('equipment')?.value||''].filter(Boolean).join(', '),txt=norm6(raw),inv={bodyweight:999};for(const [key,aliases] of Object.entries(EQ_ALIASES)){let best=0;for(const a0 of aliases){const a=norm6(a0);if(!txt.includes(a))continue;const re1=new RegExp('(\\d+)\\s*(?:x\\s*)?'+a.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')),re2=new RegExp(a.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\s*(?:x\\s*)?(\\d+)'),m=txt.match(re1)||txt.match(re2);best=Math.max(best,m?+m[1]:1)}if(best)inv[key]=best}return inv}
function minimumNeeded(a,group){if(a.eq==='bodyweight')return 0;return Math.max(1,Math.ceil(group/Math.max(1,a.per||4)))}
function finishProfile(){const v=socialCfg().finish;if(v==='Leves')return{rpe:5,doms:0};if(v==='Treinados')return{rpe:7,doms:1};if(v==='Puxado')return{rpe:8,doms:2};return{rpe:6,doms:1}}
function eligibleActivities(){const cfg=socialCfg(),inv=parseInventory(),group=+($s('groupSize')?.value||12),fp=finishProfile();let arr=SOCIAL_BANK.filter(a=>a.rpe<=fp.rpe&&a.doms<=fp.doms);if(cfg.format!=='Automático')arr=arr.filter(a=>a.format===cfg.format||a.format==='Grupo');return arr.filter(a=>a.eq==='bodyweight'||(inv[a.eq]||0)>=minimumNeeded(a,group))}
function inventoryHint(){const box=$s('socialInventoryHint');if(!box)return;const cfg=socialCfg(),group=+($s('groupSize')?.value||12),inv=parseInventory(),arr=eligibleActivities(),parts=[];for(const [k,v] of Object.entries(inv)){if(k!=='bodyweight')parts.push(`${k}: ${v}`)}const ball=inv.ball||0;let team='';if(ball){const teams=Math.min(ball,Math.max(1,Math.floor(group/3)));if(teams)team=` Com ${group} pessoas e ${ball} bola(s), a app pode organizar até ${teams} grupo(s) com bola sem concentrar toda a turma numa única estação.`}box.innerHTML=`<b>${cfg.pct}% social · saída: ${esc6(cfg.finish)}</b><br>${parts.length?'Disponível: '+esc6(parts.join(' · ')):'Sem quantidades declaradas: serão priorizadas dinâmicas de peso corporal e o material escolhido no filtro principal.'} · ${arr.length} dinâmica(s) compatíveis.${team}`}
function shuffle6(a){const x=a.slice();for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function socialExercise(a,minutes){const eqLabel=a.eq==='bodyweight'?'Peso corporal':a.eq==='ball'?'Bola':a.eq==='cones'?'Cones':a.eq==='kb'?'Kettlebell':a.eq==='trx'?'TRX':a.eq==='band'?'Elástico':a.eq==='hanging'?'Barras suspensas':a.eq==='step'?'Step':a.eq;return{id:'SOC-'+a.id+'-'+Date.now()+'-'+Math.random().toString(36).slice(2,6),name:a.name,canonical:'social '+a.id,family:'Social / Cooperativo',source:'BLUE_SOCIAL',source_confidence:'BLUE_PROGRAMMING',role:'Parte fundamental',phase:'Social',position:a.position,region:'Full body',pattern:a.pattern,equipment:eqLabel,level:'Geral',complexity:'Base/Geral',status:'REFERENCE',objective:a.objective,notes:a.rule,userNotes:`Organização: ${a.format}. Material: ${eqLabel}. Intensidade alvo aproximada: RPE ${a.rpe}/10. ${a.rule}`,time:`${minutes} min`}}
function makeSocialBlock(minutes,index=0){const arr=eligibleActivities(),chosen=shuffle6(arr.length?arr:SOCIAL_BANK.filter(a=>a.eq==='bodyweight')).slice(0,Math.max(2,Math.min(5,Math.round(minutes/4)))),each=Math.max(2,Math.round(minutes/chosen.length));return{phase:index?'Jogo / equipa — bloco '+(index+1):'Bloco social / cooperativo',minutes,exercises:chosen.map(a=>socialExercise(a,each))}}
function rescaleRegular(blocks,targetMinutes){const regular=blocks.filter(b=>!/retorno|calma|cool/i.test(b.phase)),total=regular.reduce((s,b)=>s+(+b.minutes||0),0)||1;regular.forEach(b=>{b.minutes=Math.max(3,Math.round((+b.minutes||0)*targetMinutes/total));try{if(typeof setTimes==='function')setTimes(b.exercises,b.minutes)}catch(e){}});return regular}
function applySocialMix(){const cfg=socialCfg(),pct=cfg.pct;if(!pct)return;let c=null;try{c=currentClass}catch(e){}if(!c?.blocks?.length)return;const duration=+c.config?.duration||+($s('duration')?.value||50),coolExisting=c.blocks.find(b=>/retorno|calma|cool/i.test(b.phase)),coolMin=Math.max(4,+coolExisting?.minutes||5),active=Math.max(15,duration-coolMin),socialMin=pct===100?active:Math.max(6,Math.round(active*pct/100));if(pct===100){const warm=Math.max(6,Math.min(9,Math.round(duration*.16))),cool=Math.max(4,Math.min(6,duration-warm-12)),main=Math.max(10,duration-warm-cool),parts=main>=30?3:2,base=Math.floor(main/parts),socialBlocks=[];for(let i=0;i<parts;i++)socialBlocks.push(makeSocialBlock(i===parts-1?main-base*(parts-1):base,i));const warmActs=SOCIAL_BANK.filter(a=>['MIRROR','TRAFFIC','NUMBER_DIR'].includes(a.id)),warmEx=shuffle6(warmActs).slice(0,2).map(a=>socialExercise(a,Math.max(3,Math.floor(warm/2)))),coolEx=SOCIAL_BANK.filter(a=>a.id==='WALK_TALK').map(a=>socialExercise(a,cool));c.blocks=[{phase:'Aquecimento social / interação',minutes:warm,exercises:warmEx},...socialBlocks,{phase:'Retorno à calma social',minutes:cool,exercises:coolEx}];c.mode=(c.mode?c.mode+' + ':'')+'SOCIAL 100%'}else{const remaining=Math.max(8,active-socialMin),coolBlock=coolExisting||{phase:'Retorno à calma',minutes:coolMin,exercises:[]},scaled=rescaleRegular(c.blocks,remaining),socialBlocks=[],n=pct>=75?3:pct>=50?2:1,base=Math.floor(socialMin/n);for(let i=0;i<n;i++)socialBlocks.push(makeSocialBlock(i===n-1?socialMin-base*(n-1):base,i));c.blocks=[...scaled,...socialBlocks,coolBlock];c.mode=(c.mode?c.mode+' + ':'')+`SOCIAL ${pct}%`}c.config={...(c.config||{}),socialMix:pct,finishState:cfg.finish,socialFormat:cfg.format,roomInventory:cfg.inventory};try{if(typeof finishClass==='function')finishClass();else{if(typeof renderBuild==='function')renderBuild();if(typeof renderFollow==='function')renderFollow()}}catch(e){console.warn('Social render',e)}addSocialSummary()}
function addSocialSummary(){let c=null;try{c=currentClass}catch(e){}const src=$s('sourceBox');if(!c||!src||!c.config?.socialMix)return;let el=$s('socialClassSummary');if(!el){el=document.createElement('div');el.id='socialClassSummary';el.className='goodbox';el.style.marginTop='8px';src.insertAdjacentElement('afterend',el)}el.innerHTML=`<b>Componente social ${c.config.socialMix}%</b> · objetivo de saída: <b>${esc6(c.config.finishState||'Ativos')}</b><br><span class="small">Dinâmicas escolhidas segundo grupo, material/quantidades declaradas e prioridade a pouca espera, interação e intensidade controlada.</span>`}
function wrapGeneration(){['scratchBtn','scratchFromSuggest'].forEach(id=>{const b=$s(id);if(!b||b.dataset.social106==='1'||typeof b.onclick!=='function')return;const old=b.onclick;b.onclick=function(...args){const r=old.apply(this,args);setTimeout(applySocialMix,0);return r};b.dataset.social106='1'});['useVideo','adaptVideo'].forEach(fn=>{if(typeof window[fn]!=='function'||window[fn].__social106)return;const old=window[fn],wrapped=function(...args){const r=old.apply(this,args);setTimeout(applySocialMix,0);return r};wrapped.__social106=true;window[fn]=wrapped})}
function patchSuggestions(){const b=$s('findBtn');if(!b||b.dataset.socialSummary106==='1'||typeof b.onclick!=='function')return;const old=b.onclick;b.onclick=function(...args){const r=old.apply(this,args);setTimeout(()=>{const s=$s('filterSummary'),cfg=socialCfg();if(s&&cfg.pct)s.innerHTML+=` · social <b>${cfg.pct}%</b> · saída <b>${esc6(cfg.finish)}</b>`},0);return r};b.dataset.socialSummary106='1'}
function versionBadge(){const h=document.querySelector('header h1');if(h)h.textContent='BLUE SYMBIOTE v10.0.6';const sub=document.querySelector('header .sub');if(sub)sub.textContent='atualização automática · filtros livres · TRAINING LAB · SOCIAL/COOPERATIVO · AUTO-FRAMES · BLUE EDU'}
function init(){if(!window.APP||!$s('config')||!$s('groupSize')){setTimeout(init,80);return}addSocialFields();wrapGeneration();patchSuggestions();versionBadge();saveSocial();console.info('BLUE SOCIAL/COOPERATIVO '+SOCIAL_VERSION+' ativo')}
init();
})();
