(()=>{
'use strict';
const V='10.1.0';
const DB_NAME='blue_symbiote_visual_learning';
const STORE='visuals';
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const stripNum=s=>String(s||'').replace(/^\s*\d+(?:\.\d+)?\s*[—-]\s*/,'').trim();
let db=null,cache=new Map(),active=null;
function app(){return window.APP||null}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE,{keyPath:'key'})};r.onsuccess=()=>{db=r.result;res(db)};r.onerror=()=>rej(r.error)})}
function allRecords(){return new Promise((res,rej)=>{const q=db.transaction(STORE,'readonly').objectStore(STORE).getAll();q.onsuccess=()=>res(q.result||[]);q.onerror=()=>rej(q.error)})}
function put(rec){return new Promise((res,rej)=>{const q=db.transaction(STORE,'readwrite').objectStore(STORE).put(rec);q.onsuccess=()=>res();q.onerror=()=>rej(q.error)})}
function del(key){return new Promise((res,rej)=>{const q=db.transaction(STORE,'readwrite').objectStore(STORE).delete(key);q.onsuccess=()=>res();q.onerror=()=>rej(q.error)})}
async function refresh(){cache=new Map((await allRecords()).map(r=>[r.key,r]));paintAll();paintLibraryBadges()}
function findAppEx(name){const A=app();if(!A)return null;const n=norm(name);return A.exercises.find(x=>norm(x.name)===n)||A.exercises.find(x=>norm(x.canonical)===n)||null}
function identity(name){const ex=findAppEx(name),canonical=norm(ex?.canonical||'');const key=canonical?'c:'+canonical:'n:'+norm(name);return{key,name:String(name||'').trim(),canonical,ex}}
function matchRecord(name){const id=identity(name);if(cache.has(id.key))return cache.get(id.key);const n=norm(name);for(const r of cache.values())if((r.aliases||[]).some(a=>norm(a)===n))return r;return null}
function cardName(card){return stripNum(card.querySelector('.exname')?.textContent||'')}
function dataToImage(file){return new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>{const im=new Image();im.onload=()=>{try{const max=1200,scale=Math.min(1,max/Math.max(im.width,im.height)),w=Math.max(1,Math.round(im.width*scale)),h=Math.max(1,Math.round(im.height*scale)),c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(im,0,0,w,h);let out;try{out=c.toDataURL('image/webp',.84)}catch(e){out=c.toDataURL('image/jpeg',.86)}res(out)}catch(e){rej(e)}};im.onerror=rej;im.src=fr.result};fr.onerror=rej;fr.readAsDataURL(file)})}
function injectStyle(){if(document.getElementById('blueLearnStyle'))return;const s=document.createElement('style');s.id='blueLearnStyle';s.textContent=`
.blueLearned{position:relative;width:100%;height:100%;min-height:118px;background:#fff;border-radius:10px;overflow:hidden;border:1px solid #cfe0eb}.blueLearned img{position:absolute;inset:0;width:100%;height:100%;object-fit:contain;background:#fff}.blueLearned.two img:nth-of-type(1){animation:blA 4.8s infinite}.blueLearned.two img:nth-of-type(2){animation:blB 4.8s infinite}.blueLearned .tag{position:absolute;left:6px;top:6px;z-index:3;background:#1671ad;color:#fff;border-radius:999px;padding:4px 7px;font-size:9px;font-weight:800}.blueLearnBtn{margin-top:5px;width:100%;border:1px solid #b8cedd;background:#f8fbfd;color:#17324a;border-radius:8px;padding:6px;font-size:10px;font-weight:800;cursor:pointer}.blueLearnBtn.has{background:#e8f4ff;border-color:#8ab8d8;color:#0b5f9e}.blueLearnModal{position:fixed;inset:0;z-index:99999;background:rgba(0,0,0,.56);display:none;align-items:center;justify-content:center;padding:16px}.blueLearnModal.open{display:flex}.blueLearnPanel{background:#fff;width:min(720px,96vw);max-height:92vh;overflow:auto;border-radius:16px;padding:18px;box-shadow:0 24px 70px rgba(0,0,0,.28)}.blueLearnPanel h3{margin:0 0 4px}.blueLearnGrid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:12px 0}.blueLearnSlot{border:1px dashed #a9bfce;border-radius:10px;min-height:160px;display:flex;align-items:center;justify-content:center;overflow:hidden;background:#f8fbfd}.blueLearnSlot img{max-width:100%;max-height:220px;object-fit:contain}.blueLearnPanel textarea{width:100%;min-height:72px;box-sizing:border-box;border:1px solid #c8d8e3;border-radius:8px;padding:9px}.blueLearnActions{display:flex;flex-wrap:wrap;gap:8px;margin-top:12px}.blueLearnActions button{border:0;border-radius:9px;padding:9px 12px;font-weight:800;cursor:pointer}.bluePrimary{background:#0b5f9e;color:#fff}.blueSecondary{background:#eef4f8;color:#17324a}.blueDanger{background:#ffe8e8;color:#8b1e1e}.blueLearnStatus{margin-top:8px;padding:8px 10px;border-radius:9px;background:#eef8ee;color:#245b2a;font-size:12px}@keyframes blA{0%,43%{opacity:1}50%,93%{opacity:0}100%{opacity:1}}@keyframes blB{0%,43%{opacity:0}50%,93%{opacity:1}100%{opacity:0}}@media(max-width:620px){.blueLearnGrid{grid-template-columns:1fr}}
`;document.head.appendChild(s)}
function learnedHtml(rec){const imgs=(rec.images||[]).filter(Boolean).slice(0,2),cls=imgs.length>1?'blueLearned two':'blueLearned';return `<div class="${cls}"><span class="tag">MINHA REFERÊNCIA</span>${imgs.map(x=>`<img src="${x}" alt="">`).join('')}</div>`}
function ensureButton(card,name){const wrap=card.querySelector('.imgbox')?.parentElement;if(!wrap||wrap.querySelector('.blueLearnBtn'))return;const rec=matchRecord(name),b=document.createElement('button');b.type='button';b.className='blueLearnBtn'+(rec?' has':'');b.textContent=rec?'VISUAL GUARDADO · EDITAR':'ADICIONAR / ENSINAR VISUAL';b.onclick=e=>{e.preventDefault();e.stopPropagation();openModal(name)};wrap.appendChild(b)}
function paintCard(card){const box=card.querySelector('.imgbox'),name=cardName(card);if(!box||!name)return;const rec=matchRecord(name);ensureButton(card,name);if(!rec||!(rec.images||[]).filter(Boolean).length)return;const hasCore=!!box.querySelector('img:not(.blueOpenVisual img):not(.blueLearned img)')&&!box.querySelector('.blueOpenVisual');if(hasCore)return;box.innerHTML=learnedHtml(rec)}
function paintAll(){document.querySelectorAll('#blocks .exercise,#scrollMode .exercise').forEach(paintCard);const step=document.getElementById('stepImg'),title=document.getElementById('stepTitle')?.textContent||'',rec=matchRecord(title);if(step&&rec&&(rec.images||[]).length)step.innerHTML=learnedHtml(rec)}
function modal(){let m=document.getElementById('blueLearnModal');if(m)return m;m=document.createElement('div');m.id='blueLearnModal';m.className='blueLearnModal';m.innerHTML=`<div class="blueLearnPanel"><h3 id="blueLearnTitle">Visual do exercício</h3><div class="small">O que guardares aqui passa a ser reutilizado automaticamente nas próximas aulas deste exercício.</div><div class="blueLearnGrid"><div><div class="blueLearnSlot" id="blueSlot0">IMAGEM 1</div><input id="blueFile0" type="file" accept="image/*" hidden><button class="blueLearnBtn" id="bluePick0">ESCOLHER IMAGEM 1</button></div><div><div class="blueLearnSlot" id="blueSlot1">IMAGEM 2</div><input id="blueFile1" type="file" accept="image/*" hidden><button class="blueLearnBtn" id="bluePick1">ESCOLHER IMAGEM 2</button></div></div><label><b>Nomes equivalentes / aliases</b></label><textarea id="blueAliases" placeholder="Ex.: Arm Circles, Círculos de ombros, Shoulder Circles"></textarea><div class="blueLearnStatus">A associação principal é automática pelo exercício. Usa aliases apenas quando sabes que outro nome representa o mesmo movimento.</div><div class="blueLearnActions"><button class="bluePrimary" id="blueSaveLearn">GUARDAR E REUTILIZAR</button><button class="blueSecondary" id="blueCloseLearn">FECHAR</button><button class="blueDanger" id="blueDeleteLearn">APAGAR REFERÊNCIA</button></div></div>`;document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m)closeModal()});document.getElementById('blueCloseLearn').onclick=closeModal;document.getElementById('bluePick0').onclick=()=>document.getElementById('blueFile0').click();document.getElementById('bluePick1').onclick=()=>document.getElementById('blueFile1').click();[0,1].forEach(i=>document.getElementById('blueFile'+i).onchange=async e=>{const f=e.target.files?.[0];if(!f)return;active.images[i]=await dataToImage(f);renderModalSlots()});document.getElementById('blueSaveLearn').onclick=saveModal;document.getElementById('blueDeleteLearn').onclick=deleteModal;return m}
function renderModalSlots(){for(let i=0;i<2;i++){const s=document.getElementById('blueSlot'+i),src=active?.images?.[i];s.innerHTML=src?`<img src="${src}" alt="">`:`IMAGEM ${i+1}`}}
function openModal(name){const id=identity(name),old=matchRecord(name);active={key:old?.key||id.key,name:id.name,canonical:id.canonical,images:[...(old?.images||[])].slice(0,2),aliases:[...(old?.aliases||[])]};while(active.images.length<2)active.images.push('');modal().classList.add('open');document.getElementById('blueLearnTitle').textContent='Visual — '+name;document.getElementById('blueAliases').value=(active.aliases||[]).join(', ');renderModalSlots()}
function closeModal(){document.getElementById('blueLearnModal')?.classList.remove('open');active=null}
async function saveModal(){if(!active)return;const aliases=document.getElementById('blueAliases').value.split(/[,;\n]+/).map(x=>x.trim()).filter(Boolean);const rec={...active,aliases:[...new Set([active.name,...aliases])],images:(active.images||[]).filter(Boolean).slice(0,2),updatedAt:new Date().toISOString(),approved:true};if(!rec.images.length)return alert('Escolhe pelo menos uma imagem.');await put(rec);closeModal();await refresh()}
async function deleteModal(){if(!active)return;if(!confirm('Apagar esta referência visual aprendida?'))return;await del(active.key);closeModal();await refresh()}
function captureExistingUploads(){document.addEventListener('change',async e=>{const input=e.target;if(!(input instanceof HTMLInputElement)||input.type!=='file'||!input.closest('.exercise'))return;const files=[...(input.files||[])].filter(f=>f.type.startsWith('image/')).slice(0,2);if(!files.length)return;const card=input.closest('.exercise'),name=cardName(card);if(!name)return;try{const id=identity(name),old=matchRecord(name),imgs=[];for(const f of files)imgs.push(await dataToImage(f));const rec={key:old?.key||id.key,name:id.name,canonical:id.canonical,aliases:[...new Set([id.name,...(old?.aliases||[])])],images:imgs,updatedAt:new Date().toISOString(),approved:true};await put(rec);await refresh()}catch(err){console.warn('BLUE visual learning upload',err)}},true)}
function paintLibraryBadges(){document.querySelectorAll('#visualList .visualCard').forEach(card=>{const name=card.querySelector('.visualTitle b')?.textContent||'';if(!name)return;let badge=card.querySelector('.blueLearnLibBadge');if(matchRecord(name)){if(!badge){badge=document.createElement('span');badge.className='blueLearnLibBadge visualCount';badge.textContent='APRENDIDO';card.querySelector('.visualTitle')?.appendChild(badge)}}else badge?.remove()})}
function exportLearned(){const arr=[...cache.values()];const blob=new Blob([JSON.stringify({version:V,createdAt:new Date().toISOString(),records:arr})],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='BLUE_VISUAIS_APRENDIDOS.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function importLearned(){const i=document.createElement('input');i.type='file';i.accept='application/json,.json';i.onchange=async()=>{try{const f=i.files?.[0];if(!f)return;const j=JSON.parse(await f.text()),arr=Array.isArray(j.records)?j.records:[];for(const r of arr)if(r?.key&&Array.isArray(r.images))await put(r);await refresh();alert('Biblioteca visual aprendida importada.')}catch(e){alert('Ficheiro de biblioteca inválido.')}};i.click()}
function addLibraryTools(){const list=document.getElementById('visualList');if(!list||document.getElementById('blueLearnTools'))return;const d=document.createElement('div');d.id='blueLearnTools';d.className='card';d.innerHTML='<b>BIBLIOTECA VISUAL APRENDENTE</b><div class="note" style="margin:5px 0 8px">As imagens que adicionares a um exercício ficam associadas e são reutilizadas automaticamente. Podes ainda ensinar nomes equivalentes.</div><div class="row"><button class="btn" id="blueExportLearn">EXPORTAR APRENDIZAGEM</button><button class="btn" id="blueImportLearn">IMPORTAR</button></div>';list.parentElement.insertBefore(d,list);document.getElementById('blueExportLearn').onclick=exportLearned;document.getElementById('blueImportLearn').onclick=importLearned}
function badge(){const h=document.querySelector('header h1');if(h)h.textContent='BLUE SYMBIOTE v10.1.0 FINAL';const s=document.querySelector('header .sub');if(s)s.textContent='MODO ESTÁVEL · BIBLIOTECA VISUAL APRENDENTE · TRAINING LAB · SOCIAL FLEXÍVEL · BLUE EDU'}
async function init(){if(!app()||!document.querySelector('header')){setTimeout(init,80);return}injectStyle();modal();badge();captureExistingUploads();await openDB();await refresh();addLibraryTools();const mo=new MutationObserver(()=>{clearTimeout(window.__blueLearnT);window.__blueLearnT=setTimeout(()=>{paintAll();paintLibraryBadges();addLibraryTools()},70)});for(const id of ['blocks','scrollMode','stepImg','stepTitle','visualList']){const el=document.getElementById(id);if(el)mo.observe(el,{childList:true,subtree:true,characterData:true})}console.info('BLUE VISUAL LEARNING '+V+' ativo')}
init();
})();