(()=>{
'use strict';
const V='10.0.7',KEY='blue_symbiote_social_placement_v10_7',$=id=>document.getElementById(id);
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const social=b=>!!b&&(/social|cooper|jogo|equipa/i.test(b.phase||'')||(b.exercises||[]).some(x=>x?.family==='Social / Cooperativo'||x?.source==='BLUE_SOCIAL'));
const cool=b=>!!b&&/retorno|calma|cool|along|stretch/i.test(b.phase||''),warm=b=>!!b&&/aquec|warm|prepara|ativ/i.test(b.phase||'');
function place(){return $('socialPlacement')?.value||'Automático / mescla'}
function save(){try{localStorage.setItem(KEY,place())}catch(e){}}
function addField(){const root=$('socialConfigBlock');if(!root||$('socialPlacement'))return;const f=document.createElement('div');f.className='field';f.innerHTML='<label>Onde usar a componente social?</label><select id="socialPlacement"><option>Automático / mescla</option><option>Só no aquecimento</option><option>Aquecimento + parte fundamental</option><option>Só na parte fundamental</option><option>Final ativo antes do retorno à calma</option><option>Aquecimento + final ativo</option><option>Aula social inteira</option></select>';root.querySelector('.grid')?.appendChild(f);try{$('socialPlacement').value=localStorage.getItem(KEY)||'Automático / mescla'}catch(e){};$('socialPlacement').onchange=()=>{const v=place(),m=$('socialMix');if(m){if(v==='Aula social inteira')m.value='100';else if((v==='Só no aquecimento'||v==='Final ativo antes do retorno à calma')&&(+m.value===0||+m.value>25))m.value='25'}save();hint()};hint()}
function hint(){const root=$('socialConfigBlock');if(!root)return;let b=$('socialPlacementHint');if(!b){b=document.createElement('div');b.id='socialPlacementHint';b.className='storageNote';b.style.marginTop='8px';root.appendChild(b)}const v=place(),map={'Automático / mescla':'Distribui a interação pela sessão conforme a percentagem escolhida.','Só no aquecimento':'Usa 6–10 min lúdicos e progressivos como aquecimento.','Aquecimento + parte fundamental':'Começa social e volta a usar dinâmicas no corpo da aula.','Só na parte fundamental':'Mantém aquecimento e retorno à calma convencionais.','Final ativo antes do retorno à calma':'Usa 6–10 min para desacelerar em movimento antes de alongar/retornar à calma.','Aquecimento + final ativo':'Interação leve no início e novamente no fim, antes do retorno à calma.','Aula social inteira':'A sessão inteira é social/cooperativa, com aquecimento e fecho apropriados.'};b.innerHTML='<b>Colocação:</b> '+esc(v)+'<br>'+esc(map[v]||map['Automático / mescla'])}
function cls(){try{return typeof currentClass!=='undefined'?currentClass:null}catch(e){return null}}
function total(bs){return bs.reduce((s,b)=>s+(+b.minutes||0),0)}
function smin(bs){return bs.filter(social).reduce((s,b)=>s+(+b.minutes||0),0)}
function setTimes(b){if(!b?.exercises?.length)return;const t=Math.max(1,Math.round((+b.minutes||1)/b.exercises.length));b.exercises.forEach(x=>x.time=t+' min')}
function addLargest(bs,n){if(n<=0)return;const a=bs.filter(b=>!social(b)&&!cool(b)).sort((x,y)=>(+y.minutes||0)-(+x.minutes||0));if(a[0]){a[0].minutes=(+a[0].minutes||0)+n;setTimes(a[0])}}
function ex(id,name,pattern,obj,rule,pos='Em pé',eq='Peso corporal'){return{id:'SOC7-'+id+'-'+Date.now()+Math.random().toString(36).slice(2,5),name,canonical:'social '+id,family:'Social / Cooperativo',source:'BLUE_SOCIAL',role:'Variável',phase:'Social',position:pos,region:'Full body',pattern,equipment:eq,level:'Geral',complexity:'Base/Geral',status:'REFERENCE',objective:obj,notes:rule,userNotes:rule,time:'3 min'}}
function warmBlock(m){const xs=[ex('MIRROR_W','Espelho em pares — aquecimento','Coordenação / reação','Aquecer e criar interação sem fadiga alta.','Em pares: um lidera passos laterais, reaches, hinge suave e squat curto; o outro copia.'),ex('TRAFFIC_W','Semáforo de movimento — aquecimento','Reação / deslocamento','Elevar gradualmente temperatura e atenção.','Verde = deslocar; amarelo = marcha/step touch; vermelho = parar e cumprir 1 movimento simples.'),ex('NUMBERS_W','Números e direções — aquecimento','Coordenação / agilidade','Preparar reação e orientação espacial.','Cada número corresponde a uma direção ou tarefa curta; sem sprint máximo.')];const a=xs.slice(0,m>=9?3:2),t=Math.max(2,Math.round(m/a.length));a.forEach(x=>x.time=t+' min');return{phase:'Aquecimento social / lúdico',minutes:m,exercises:a}}
function finalBlock(m){const xs=[ex('WALK_F','Caminhada em pares + mobilidade','Locomotion / mobilidade','Desacelerar sem parar bruscamente.','Caminhar em pares; ao sinal fazer mobilidade/respiração leve e retomar.'),ex('MIRROR_F','Espelho lento em pares','Coordenação / controlo','Reduzir intensidade mantendo interação.','Um lidera movimentos lentos e amplos; o parceiro acompanha. Trocar ao sinal.')];if(/bola|ball|medicine/.test(norm([$('roomInventory')?.value,$('equipment')?.value].join(' '))))xs.push(ex('PASS_F','Passe leve + rotação controlada','Rotação / passe','Baixar intensidade com coordenação leve.','Em roda pequena, passes lentos com rotação torácica confortável.','Sentado','Bola'));const a=xs.slice(0,m>=9?3:2),t=Math.max(2,Math.round(m/a.length));a.forEach(x=>x.time=t+' min');return{phase:'Desaceleração ativa / social',minutes:m,exercises:a}}
function main(bs,ss){const out=bs.filter(b=>!social(b)),ci=out.findIndex(cool),i=ci>=0?ci:out.length;ss.forEach((b,n)=>{b.phase=ss.length>1?'Parte fundamental — social/cooperativo '+(n+1):'Parte fundamental — social/cooperativo'});out.splice(i,0,...ss);return out}
function distribute(bs,ss){const reg=bs.filter(b=>!social(b)),ci=reg.findIndex(cool),cb=ci>=0?reg.splice(ci,1)[0]:null,out=[];let j=0;reg.forEach((b,i)=>{out.push(b);if(j<ss.length&&i>=Math.max(0,Math.floor(reg.length/3)-1)){ss[j].phase='Bloco social / cooperativo — mescla';out.push(ss[j++])}});while(j<ss.length){ss[j].phase='Bloco social / cooperativo — mescla';out.push(ss[j++])}if(cb)out.push(cb);return out}
function adjust(){const c=cls(),v=place();if(!c?.blocks?.length||!c.config?.socialMix||c.config.socialPlacementApplied===v)return;let bs=c.blocks.map(b=>({...b,exercises:(b.exercises||[]).map(x=>JSON.parse(JSON.stringify(x)))})),ss=bs.filter(social),before=total(bs);if(!ss.length)return;if(v==='Aula social inteira'){c.config.socialPlacement=v;c.config.socialPlacementApplied=v;summary();return}if(v==='Automático / mescla')bs=distribute(bs,ss);else if(v==='Só na parte fundamental')bs=main(bs,ss);else if(v==='Só no aquecimento'){const sm=smin(bs),wi=bs.findIndex(b=>warm(b)&&!social(b)),wm=wi>=0?(+bs[wi].minutes||0):0;if(wi>=0)bs.splice(wi,1);bs=bs.filter(b=>!social(b));const t=Math.max(6,Math.min(10,wm||sm||8));bs.unshift(warmBlock(t));addLargest(bs,Math.max(0,sm+wm-t))}else if(v==='Final ativo antes do retorno à calma'){const sm=smin(bs);bs=bs.filter(b=>!social(b));const t=Math.max(6,Math.min(10,sm||8)),ci=bs.findIndex(cool);bs.splice(ci>=0?ci:bs.length,0,finalBlock(t));addLargest(bs,Math.max(0,sm-t))}else if(v==='Aquecimento + final ativo'){const sm=smin(bs),wi=bs.findIndex(b=>warm(b)&&!social(b)),wm=wi>=0?(+bs[wi].minutes||0):0;if(wi>=0)bs.splice(wi,1);bs=bs.filter(b=>!social(b));const w=Math.max(5,Math.min(8,wm||7)),f=Math.max(5,Math.min(8,Math.round((sm+wm)*.45)||6));bs.unshift(warmBlock(w));const ci=bs.findIndex(cool);bs.splice(ci>=0?ci:bs.length,0,finalBlock(f));addLargest(bs,Math.max(0,sm+wm-w-f))}else if(v==='Aquecimento + parte fundamental'){const sm=smin(bs),wi=bs.findIndex(b=>warm(b)&&!social(b)),wm=wi>=0?(+bs[wi].minutes||0):0;if(wi>=0)bs.splice(wi,1);bs=bs.filter(b=>!social(b));const w=Math.max(5,Math.min(8,wm||7));bs.unshift(warmBlock(w));ss.forEach(b=>{b.phase='Parte fundamental — social/cooperativo';setTimes(b)});const ci=bs.findIndex(cool);bs.splice(ci>=0?ci:bs.length,0,...ss);addLargest(bs,Math.max(0,sm+wm-w-smin(ss)))}const d=before-total(bs);if(d>0)addLargest(bs,d);c.blocks=bs;c.config={...(c.config||{}),socialPlacement:v,socialPlacementApplied:v};try{if(typeof finishClass==='function')finishClass();else{renderBuild?.();renderFollow?.()}}catch(e){console.warn(e)}summary()}
function summary(){const c=cls(),src=$('sourceBox');if(!c?.config?.socialMix||!src)return;let el=$('socialPlacementSummary');if(!el){el=document.createElement('div');el.id='socialPlacementSummary';el.className='goodbox';el.style.marginTop='8px';($('socialClassSummary')||src).insertAdjacentElement('afterend',el)}el.innerHTML='<b>Uso social:</b> '+esc(c.config.socialPlacement||place())+'<br><span class="small">Pode funcionar como aquecimento, mescla na parte fundamental ou desaceleração ativa antes do retorno à calma.</span>'}
function wrap(){['scratchBtn','scratchFromSuggest'].forEach(id=>{const b=$(id);if(!b||b.dataset.place107==='1'||typeof b.onclick!=='function')return;const old=b.onclick;b.onclick=function(...a){const r=old.apply(this,a);setTimeout(adjust,50);return r};b.dataset.place107='1'});['useVideo','adaptVideo'].forEach(fn=>{if(typeof window[fn]!=='function'||window[fn].__place107)return;const old=window[fn],nw=function(...a){const r=old.apply(this,a);setTimeout(adjust,50);return r};nw.__place107=true;window[fn]=nw})}
function badge(){const h=document.querySelector('header h1');if(h)h.textContent='BLUE SYMBIOTE v10.0.7';const s=document.querySelector('header .sub');if(s)s.textContent='atualização automática · TRAINING LAB · SOCIAL FLEXÍVEL · AUTO-FRAMES · BLUE EDU'}
function init(){if(!$('socialConfigBlock')||!window.APP){setTimeout(init,80);return}addField();wrap();badge();console.info('BLUE SOCIAL PLACEMENT '+V+' ativo')}
init();
})();