(()=>{
'use strict';
const V='10.2.0';
const SUPABASE_URL='https://vfwkxlcamtcrmdsuxmyz.supabase.co';
const SUPABASE_KEY='sb_publishable_u47bb62djMLkz2-Ib_1tMg_mjGeu4z1';
const AUTH_KEY='blue_symbiote_auth_session_v10_2';
const AUTHZ_KEY='blue_symbiote_authorized_user_v10_2';
const CLOUD_META='blue_symbiote_cloud_meta_v10_2';
const DEVICE_KEY='blue_symbiote_device_id_v10_2';
let session=null,member=null,cloudDirty=false,cloudTimer=null,restoring=false,lastRemoteUpdatedAt='',syncBusy=false;
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function deviceId(){let id=localStorage.getItem(DEVICE_KEY);if(!id){id=(crypto.randomUUID?crypto.randomUUID():'dev-'+Date.now()+'-'+Math.random().toString(36).slice(2));localStorage.setItem(DEVICE_KEY,id)}return id}
function loadSession(){try{return JSON.parse(localStorage.getItem(AUTH_KEY)||'null')}catch(e){return null}}
function saveSession(s){session=s||null;if(s)localStorage.setItem(AUTH_KEY,JSON.stringify(s));else localStorage.removeItem(AUTH_KEY)}
function authHeaders(extra={}){return {'apikey':SUPABASE_KEY,'Authorization':'Bearer '+session.access_token,...extra}}
async function authRequest(path,opts={}){const r=await fetch(SUPABASE_URL+'/auth/v1'+path,{...opts,headers:{'apikey':SUPABASE_KEY,'Content-Type':'application/json',...(opts.headers||{})}});const txt=await r.text();let data={};try{data=txt?JSON.parse(txt):{}}catch(e){data={message:txt}}if(!r.ok)throw new Error(data.msg||data.message||data.error_description||('HTTP '+r.status));return data}
async function login(email,password){const data=await authRequest('/token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})});data.expires_at=Math.floor(Date.now()/1000)+(data.expires_in||3600);saveSession(data);return data}
async function refreshSession(){if(!session?.refresh_token)throw new Error('Sessão sem refresh token.');const data=await authRequest('/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:session.refresh_token})});data.expires_at=Math.floor(Date.now()/1000)+(data.expires_in||3600);saveSession(data);return data}
async function ensureFreshSession(){session=loadSession();if(!session)return null;const exp=Number(session.expires_at||0);if(exp&&exp-Math.floor(Date.now()/1000)>90)return session;try{return await refreshSession()}catch(e){const cached=localStorage.getItem(AUTHZ_KEY);if(cached&&session?.user?.id===cached&&!navigator.onLine)return session;saveSession(null);return null}}
async function fetchMember(){const uid=session?.user?.id;if(!uid)return null;const u=SUPABASE_URL+'/rest/v1/blue_symbiote_members?select=user_id,email,display_name,role,active&user_id=eq.'+encodeURIComponent(uid)+'&limit=1';try{const r=await fetch(u,{headers:authHeaders()});if(!r.ok)throw new Error('HTTP '+r.status);const arr=await r.json();const m=arr?.[0]||null;if(m?.active){localStorage.setItem(AUTHZ_KEY,uid);member=m;return m}return null}catch(e){if(!navigator.onLine&&localStorage.getItem(AUTHZ_KEY)===uid){member={user_id:uid,email:session.user?.email||'',display_name:'',role:'offline',active:true};return member}throw e}}
async function logout(){try{if(session?.access_token)await fetch(SUPABASE_URL+'/auth/v1/logout',{method:'POST',headers:authHeaders()})}catch(e){}saveSession(null);member=null;localStorage.removeItem(CLOUD_META);location.reload()}
async function recover(email){if(!email)throw new Error('Escreve primeiro o teu email.');return authRequest('/recover',{method:'POST',body:JSON.stringify({email})})}
function syncableKey(k){return k.startsWith('blue_symbiote_')&&![AUTH_KEY,AUTHZ_KEY,CLOUD_META,DEVICE_KEY].includes(k)}
function snapshot(){const ls={};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&syncableKey(k))ls[k]=localStorage.getItem(k)}return{schemaVersion:1,appVersion:V,localStorage:ls}}
function cloudMeta(){try{return JSON.parse(localStorage.getItem(CLOUD_META)||'{}')||{}}catch(e){return{}}}
function setCloudMeta(o){localStorage.setItem(CLOUD_META,JSON.stringify({...cloudMeta(),...o}))}
async function getRemote(){const uid=session.user.id;const u=SUPABASE_URL+'/rest/v1/blue_symbiote_state?select=user_id,payload,revision,updated_at,device_id&user_id=eq.'+encodeURIComponent(uid)+'&limit=1';const r=await fetch(u,{headers:authHeaders()});if(!r.ok)throw new Error('Cloud GET '+r.status);return(await r.json())?.[0]||null}
async function pushRemote(){if(syncBusy||restoring||!session||!navigator.onLine)return;syncBusy=true;try{const row={user_id:session.user.id,payload:snapshot(),revision:Date.now(),device_id:deviceId(),updated_at:new Date().toISOString()};const r=await fetch(SUPABASE_URL+'/rest/v1/blue_symbiote_state?on_conflict=user_id',{method:'POST',headers:authHeaders({'Content-Type':'application/json','Prefer':'resolution=merge-duplicates,return=representation'}),body:JSON.stringify(row)});if(!r.ok)throw new Error('Cloud POST '+r.status);const arr=await r.json();const saved=arr?.[0]||row;lastRemoteUpdatedAt=saved.updated_at||row.updated_at;setCloudMeta({updatedAt:lastRemoteUpdatedAt,revision:saved.revision||row.revision});cloudDirty=false;paintAccount('SINCRONIZADO')}catch(e){console.warn('BLUE cloud push',e);paintAccount(navigator.onLine?'ERRO NUVEM':'OFFLINE')}finally{syncBusy=false}}
function schedulePush(){if(restoring||!session)return;cloudDirty=true;clearTimeout(cloudTimer);cloudTimer=setTimeout(pushRemote,1200);paintAccount('A SINCRONIZAR…')}
async function applyRemote(remote){const ls=remote?.payload?.localStorage||{};restoring=true;try{for(const[k,v]of Object.entries(ls))if(syncableKey(k)){if(v==null)localStorage.removeItem(k);else localStorage.setItem(k,String(v))}}finally{restoring=false}lastRemoteUpdatedAt=remote.updated_at||'';setCloudMeta({updatedAt:lastRemoteUpdatedAt,revision:remote.revision||0})}
async function initialCloudSync(){if(!navigator.onLine){paintAccount('OFFLINE');return}const remote=await getRemote();const local=snapshot();const localHasMeaningful=Object.keys(local.localStorage).some(k=>k!=='blue_symbiote_frame_meta_v10_5');if(!remote){await pushRemote();return}const meta=cloudMeta();if(!meta.updatedAt){if(remote.payload?.localStorage&&Object.keys(remote.payload.localStorage).length){await applyRemote(remote);location.reload();return}if(localHasMeaningful){await pushRemote();return}}lastRemoteUpdatedAt=remote.updated_at||meta.updatedAt||'';paintAccount('SINCRONIZADO')}
async function pullRemote(){if(syncBusy||cloudDirty||!session||!navigator.onLine)return;try{const remote=await getRemote();if(!remote)return;const known=cloudMeta().updatedAt||lastRemoteUpdatedAt||'';if(remote.updated_at&&(!known||remote.updated_at>known)&&remote.device_id!==deviceId()){await applyRemote(remote);location.reload()}}catch(e){console.warn('BLUE cloud pull',e)}}
function hookStorage(){if(window.__BLUE_AUTH_STORAGE_HOOKED)return;window.__BLUE_AUTH_STORAGE_HOOKED=true;const proto=Storage.prototype,origSet=proto.setItem,origRemove=proto.removeItem,origClear=proto.clear;proto.setItem=function(k,v){const r=origSet.call(this,k,v);if(this===localStorage&&syncableKey(String(k)))schedulePush();return r};proto.removeItem=function(k){const r=origRemove.call(this,k);if(this===localStorage&&syncableKey(String(k)))schedulePush();return r};proto.clear=function(){const r=origClear.call(this);if(this===localStorage)schedulePush();return r}}
function injectStyle(){if($('blueAuthStyle'))return;const s=document.createElement('style');s.id='blueAuthStyle';s.textContent=`.blueAuthGate{position:fixed;inset:0;z-index:2147483000;background:linear-gradient(155deg,#eaf3f8,#f8fbfd);display:flex;align-items:center;justify-content:center;padding:18px}.blueAuthCard{width:min(430px,94vw);background:#fff;border:1px solid #cfe0eb;border-radius:20px;box-shadow:0 24px 80px rgba(15,54,80,.2);padding:24px}.blueAuthLogo{font-size:28px;font-weight:900;color:#0b5f9e}.blueAuthSub{margin:5px 0 18px;color:#516575;line-height:1.4}.blueAuthCard label{display:block;font-size:12px;font-weight:800;margin:11px 0 5px}.blueAuthCard input{width:100%;box-sizing:border-box;border:1px solid #bcd0dd;border-radius:11px;padding:12px 13px;font-size:16px}.blueAuthBtn{width:100%;border:0;border-radius:11px;padding:12px 14px;margin-top:14px;background:#0b5f9e;color:#fff;font-weight:900;font-size:15px;cursor:pointer}.blueAuthLink{width:100%;border:0;background:transparent;color:#0b5f9e;font-weight:800;padding:10px;cursor:pointer}.blueAuthMsg{min-height:20px;margin-top:10px;font-size:12px;line-height:1.35}.blueAuthErr{color:#8b1e1e}.blueAuthOk{color:#25672c}.blueAccount{display:flex;gap:7px;align-items:center;flex-wrap:wrap;margin-top:8px}.blueAccountPill{border:1px solid #b9cfdd;background:#f7fbfd;border-radius:999px;padding:6px 9px;font-size:11px;font-weight:800;color:#17324a}.blueLogout{border:0;background:#eaf3f8;border-radius:999px;padding:6px 9px;font-size:11px;font-weight:800;cursor:pointer}`;document.head.appendChild(s)}
function gate(){let g=$('blueAuthGate');if(g)return g;g=document.createElement('div');g.id='blueAuthGate';g.className='blueAuthGate';g.innerHTML=`<div class="blueAuthCard"><div class="blueAuthLogo">BLUE SYMBIOTE</div><div class="blueAuthSub"><b>Entrar</b><br>Uma conta. A mesma aplicação no PC, portátil e telemóvel.</div><label>Email</label><input id="blueAuthEmail" type="email" autocomplete="username" inputmode="email"><label>Palavra-passe</label><input id="blueAuthPass" type="password" autocomplete="current-password"><button id="blueAuthLogin" class="blueAuthBtn">ENTRAR</button><button id="blueAuthRecover" class="blueAuthLink">RECUPERAR PALAVRA-PASSE</button><div id="blueAuthMsg" class="blueAuthMsg"></div></div>`;document.body.appendChild(g);const last=localStorage.getItem('blue_symbiote_last_email_v10_2');if(last)$('blueAuthEmail').value=last;$('blueAuthPass').addEventListener('keydown',e=>{if(e.key==='Enter')$('blueAuthLogin').click()});$('blueAuthLogin').onclick=async()=>{const b=$('blueAuthLogin'),msg=$('blueAuthMsg'),email=$('blueAuthEmail').value.trim(),pass=$('blueAuthPass').value;if(!email||!pass){msg.className='blueAuthMsg blueAuthErr';msg.textContent='Preenche email e palavra-passe.';return}b.disabled=true;msg.className='blueAuthMsg';msg.textContent='A entrar…';try{await login(email,pass);const m=await fetchMember();if(!m){saveSession(null);throw new Error('Esta conta não tem acesso ao BLUE Symbiote.')}localStorage.setItem('blue_symbiote_last_email_v10_2',email);g.remove();await startAuthorized()}catch(e){msg.className='blueAuthMsg blueAuthErr';msg.textContent=String(e.message||e)}finally{b.disabled=false}};$('blueAuthRecover').onclick=async()=>{const msg=$('blueAuthMsg'),email=$('blueAuthEmail').value.trim();try{await recover(email);msg.className='blueAuthMsg blueAuthOk';msg.textContent='Pedido enviado. Consulta o email associado à conta BLUE.'}catch(e){msg.className='blueAuthMsg blueAuthErr';msg.textContent=String(e.message||e)}};return g}
function paintAccount(status='SINCRONIZADO'){const h=document.querySelector('header');if(!h||!member)return;let x=$('blueAccount');if(!x){x=document.createElement('div');x.id='blueAccount';x.className='blueAccount';h.appendChild(x)}x.innerHTML=`<span class="blueAccountPill">${esc(member.display_name||member.email||'Conta BLUE')}</span><span class="blueAccountPill" id="blueCloudState">${esc(status)}</span><button class="blueLogout" id="blueLogout">SAIR</button>`;$('blueLogout').onclick=logout}
async function registerSW(){if(!('serviceWorker'in navigator)||location.protocol==='file:')return;try{const reg=await navigator.serviceWorker.register('./service-worker.js?v='+V,{scope:'./',updateViaCache:'none'});reg.update().catch(()=>{})}catch(e){console.warn('SW',e)}}
async function startAuthorized(){hookStorage();paintAccount(navigator.onLine?'A LIGAR À NUVEM…':'OFFLINE');try{await initialCloudSync()}catch(e){console.warn('Initial cloud sync',e);paintAccount(navigator.onLine?'ERRO NUVEM':'OFFLINE')}registerSW();window.addEventListener('online',()=>{paintAccount('A LIGAR À NUVEM…');pullRemote();pushRemote()});window.addEventListener('offline',()=>paintAccount('OFFLINE'));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')pullRemote();else if(cloudDirty)pushRemote()});setInterval(()=>{if(document.visibilityState==='visible')pullRemote()},45000)}
async function init(){injectStyle();session=await ensureFreshSession();if(!session){gate();return}try{const m=await fetchMember();if(!m){saveSession(null);gate();return}await startAuthorized()}catch(e){console.warn('Auth member check',e);if(!navigator.onLine&&localStorage.getItem(AUTHZ_KEY)===session?.user?.id){member={user_id:session.user.id,email:session.user.email||'',active:true};await startAuthorized()}else{saveSession(null);gate()}}}
init();
})();
